services:
  db:
    image: postgres:latest
    container_name: stack-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - bags_data:/var/lib/postgresql/data

  api:
    container_name: bags-api
    mem_limit: 512m
    image: "ghcr.io/abramowichana/bags:${API_VERSION}"
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8080"

  fake:
    container_name: "fake-api"
    image: "ghcr.io/pablobaratta/fake-api:${FAKE_VERSION}"
    volumes:
      - ./testutil/balances.json:/app/balances.json
    environment:
      EXTERNAL_API_URL: "${API_URL}"
      EXTERNAL_API_TOKEN: "${EXTERNAL_API_TOKEN}"
    ports:
      - "${FAKE_PORT}:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"


  frontend:
    image: "ghcr.io/abramowichana/bags-front:${FRONT_VERSION}"
    ports:
      - "${FRONT_PORT}:80"
volumes:
  bags_data: