services:
  db:
    image: postgres:latest
    container_name: stack-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - bags_data:/var/lib/postgresql/data

  api:
    container_name: bags-api
    mem_limit: 512m
    image: "ghcr.io/abramowichana/bags:${API_VERSION}"
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8080"

  frontend:
    image: "ghcr.io/abramowichana/bags-front:${FRONT_VERSION}"
    ports:
      - "${FRONT_PORT}:80"
volumes:
  bags_data: